### ISSUE TITLE
Trickster with influxdb prometheus endpoint needs post_uri

### ISSUE THREAD

**Issue by tehlers320** [trickstercache/trickster#272]
There needs to be a post_uri addon unless i mis-understand how this functions. 

The schema for using the influxdb URL  build into influxdb is:

`http://myinflux.server.com:8086/api/v1/prom/read?db=somedatabase&u=someuser&p=somepassword`

The only way i could do this was using nginx.

**Comment by jranson** [comment]
Hi @tehlers320 - unfortunately we weren't quite able to get the prom endpoint into 1.0, but I will have it ready to go in the 1.2 release slated for Q2. This feature requires being able to decouple some internals of the the Trickster codebase, which will be completed when we implement the Common Time Series Format (#348) in Trickster 1.2. So I will slate this issue that release, and you can keep an eye on the status here.

You should be able to use the path customizations to accomplish Authorization header insertion ([docs](https://github.com/Comcast/trickster/blob/master/docs/paths.md#suggested-use-cases). Would you mind checking to see if that meets your needs? We'll keep this issue open until the prom endpoint is released.

I think it would make sense to implement an Origin-level Authorization interface, that would obviously include Basic Auth out of the box. I will write up a separate issue for this enhancement and we'll get it on the roadmap.

Stay tuned!

**Comment by jranson** [comment]
BTW, an example of appending an authorization header to Influxdb:

```toml
[origins]
  [origins.example]
  origin_type = 'influxdb' <and other origin-level configs>
    [origins.example.paths]
      [origins.example.paths.'/query-GET-POST']
        [origins.example.paths.'/query-GET-POST'.request_headers]
        'Authorization' = 'basic <your-hash>'
```

That's a lot of TOML, and we are looking at some point in the future joining the YAML revolution (and supporting both formats for a period of transition), which will greatly simplify managing path-level behavior customizations.
