### ISSUE TITLE
Request Rewrite Example

### ISSUE THREAD

**Issue by base698** [trickstercache/trickster#598]
For something like:
```
rules:
  example-user-router:
    # default route is reader cluster
    next_route: example-reader-cluster

    input_source: path
    input_type: string
    operation: rmatch      # perform regex match against the path to see if it matches 'writer
    operation_arg: '^.*%7Bmylabel%3D%22([a-z0-9]{3})%22.*$'
    cases:
      rmatch-true:
        matches: [ 'true' ] # rmatch returns true when the input matches the regex; update next_route
        next_route: example-writer-cluster
```

Trying to take the capture group above and add into the hostname as a prefix.  Basically like a relabel_config in prometheus.  I didn't see an examples on how to do it.  Most of the examples for rewrites involve fixed values like here: https://github.com/trickstercache/trickster/blob/main/docs/request_rewriters.md#header-set

Looking through the source: https://github.com/trickstercache/trickster/blob/0cf4524824c6916aade49dbd99ef360e61426289/pkg/proxy/request/rewriter/rewrite_instructions_test.go#L71

Looks like that uses a ${trickster} var.  Don't see where it originated.
