### ISSUE TITLE
Can't make ALB work with Grafana

### ISSUE THREAD

**Issue by tonychoe** [trickstercache/trickster#821]
Thanks for making a great project.

I have been testing to use Trickster to send query to Mimir backend in multiple cloud regions and merge response.

I've used an ALB with TSM mechanism and multiple Mimir backends in the pool. This set up works well by using curl command. I could get a response both from the ALB path and each backend's path. Health check works great. 

However, when I configured Trickster as Grafana data source and tested it, Grafana gets the 404 error.

Here's my set up:

* Using the binary built from the latest commit (also tried the container image with the main tag)

* Into the Grafana data source, I've configured the Prometheus URL like http://trickster.trickster.svc.cluster.local.:80/lab_alb_1 

* Trickster configuration below.

```
    lab_alb_1:
      provider: alb
      alb:
        mechanism: tsm 
        pool:  
          - lab2
          - lab4
        healthy_floor: 1
    # Mimir backend 
    lab1:
      provider: 'prometheus'
      origin_url: 'http://query-frontend.mimir.svc.cluster.local.:8080/prometheus'
      path_routing_disabled: false  
      #req_rewriter_name: lab
      healthcheck:
        host: 'query-frontend.mimir.svc.cluster.local.:8080'
        verb: GET
        scheme: http
        path: /prometheus/api/v1/status/buildinfo 
        expected_codes: [ 200 ]
        timeout: 1000ms      
        interval: 5000ms   
        failure_threshold: 3
        recovery_threshold: 3 
      prometheus:
        labels:
          oci_region: lab2 # add label to the result to avoid collision
    # Identical to lab1 except the backend path and prometheus labels
    lab2:
      provider: 'prometheus'
      origin_url: 'http://query-frontend.mimir.svc.cluster.local.:8080/prometheus'
      path_routing_disabled: false  
      #req_rewriter_name: lab
      healthcheck:
        host: 'query-frontend.mimir.svc.cluster.local.:8080'
        verb: GET
        scheme: http
        path: /prometheus/api/v1/status/buildinfo 
        expected_codes: [ 200 ]
        timeout: 1000ms      
        interval: 5000ms   
        failure_threshold: 3
        recovery_threshold: 3 
      prometheus:
        labels:
          oci_region: lab2 # add label to the result to avoid collision
```

The error log in Grafana says
```
logger=tsdb.prometheus endpoint=checkHealth pluginId=prometheus dsName=trickster-lab dsUID=bekxiwtqm3vggc uname=tonylab_admin traceID=147c8cc8a377f3ad24bb443de8c9adca t=2025-05-06T03:43:58.145125265Z level=warn msg="Failed to get prometheus heuristics" err="failed to get buildinfo: failed to unmarshal JSON: invalid character '\\x1f' looking for beginning of value"
```

This looks like the same issue reported in https://github.com/trickstercache/trickster/issues/599
