### ISSUE TITLE
Injecting Prometheus labels do not work

### ISSUE THREAD

**Issue by tonychoe** [trickstercache/trickster#843]
Hello Tricksters!

Thanks for releasing the Beta 3 which I have been testing. 

One issue I am facing is with injecting Prometheus labels per this guide: 
https://github.com/trickstercache/trickster/blob/main/docs/prometheus.md

I couldn't make the labels attached to the returning time series. 

- Either the case of single backend or multiple backends via ALB w/ TSM. 
- Time series I am querying from these backends are unique, so I don't need to add the Prom label by using Trickster, but I was testing the feature.

Please advice.

<details>
<summary>Trickster configuration (click to expand)</summary>

Here's a copy of one of backend config

```
  us-phoenix-1:
    healthcheck:
      expected_codes:
      - 200
      failure_threshold: 3
      headers:
        XXX
      host: host.us-phoenix-1.domain.oraclecloud.com.
      interval: 5000ms
      path: /prometheus/api/v1/status/buildinfo
      recovery_threshold: 3
      scheme: https
      timeout: 1000ms
      verb: GET
    origin_url: https://host.us-phoenix-1.domain.oraclecloud.com.
    prometheus:
      labels:
        trickster_label: us-phoenix-1
    provider: prometheus
    req_rewriter_name: oc1_authentication
```
</details>

**Comment by jranson** [comment]
Hey Tony, thanks for giving it a spin.

I was able to verify that the label injector works, at least using a simple test config. I created the one attached, which will work with the Trickster [developer environment](https://github.com/trickstercache/trickster/tree/main/docs/developer/environment). Couple notes on `test-labels-and-tsm.yaml`:

* This defines 2 backends (`prom1` and `prom2`) for the same prom container in the dev environment. One uses `127.0.0.1` and the other uses `localhost` causing Trickster to consider them as completely different endpoints. They each have a `testlabel` label injected with a value matching their respective backend name.
* I included a TSM ALB backend so that we can re-use it for #844
* I included a label with underscores to make sure there is not a permitted characters issue (and there is not)

Since this simple test of labels seems to work, it's possible some features (e.g., request rewriter) are interfering with the injections. I'll be double checking that next!

To verify labels (w/ simple config):

With docker running, run `make developer-start` or (`cd docs/developer/environment && docker compose up -d prometheus` to avoid starting up the whole stack). Then, back in the project root, run `go run cmd/trickster/main.go -config <path-to-test-labels-and-tsm.yaml>` to start up Trickster with the simple test config. The Prom container in the Developer Environment will automatically start scraping your Trickster process's metrics page. Wait about one minute and Prometheus will have data available for querying.

I have this script (`trk-req-prom`) to easily make prom range queries to various Trickster backends using recent timestamps. (Note, if you are not on a mac, you'll need to change the docker localhost label value to your own)

```sh
#!/bin/sh

# trk-req-prom - make easy test calls to different Trickster prometheus backends
#
# BACKEND=my-backend-name trk-req-prom  | jq
#

T1=$(expr $(date +%s) - 300)
T2=$(expr $(date +%s) - 0)

CURL=/usr/bin/curl

URL="http://127.0.0.1:8480/${BACKEND:-prom1}/api/v1/query_range?query=go_memstats_alloc_bytes%7Binstance%3D%22docker.for.mac.localhost%3A8481%22%7D&start=${T1}&end=${T2}&step=60"

$CURL -sS "$@" $URL 
```

So now I can test each of the backends out to confirm their labels.

prom1:
```
$ trk-req-prom | jq           # uses prom1 by default
{
  "status": "success",
  "data": {
    "resultType": "matrix",
    "result": [
      {
        "metric": {
          "__name__": "go_memstats_alloc_bytes",
          "instance": "docker.for.mac.localhost:8481",
          "job": "trickster",
          "test_underscore": "works",      <---- test_underscore injects correctly
          "testlabel": "prom1"             <---- testlabel injects correctly
        },
        "values": [
          [
            ...
          ]
        ]
      }
    ]
  }
}
```

prom2:
```
$ BACKEND=prom2 trk-req-prom | jq
{
  "status": "success",
  "data": {
    "resultType": "matrix",
    "result": [
      {
        "metric": {
          "__name__": "go_memstats_alloc_bytes",
          "instance": "docker.for.mac.localhost:8481",
          "job": "trickster",
          "test_underscore": "works",      <---- test_underscore injects correctly
          "testlabel": "prom2"             <---- testlabel injects correctly
        },
        "values": [
          [
            ...
          ]
        ]
      }
    ]
  }
}
```

alb-tsm (⚠️ [not properly merging in prom2](https://github.com/trickstercache/trickster/issues/843)):
```
$ BACKEND=alb-tsm trk-req-prom | jq
{
  "status": "success",
  "data": {
    "resultType": "matrix",
    "result": [
      {
        "metric": {
          "__name__": "go_memstats_alloc_bytes",
          "instance": "docker.for.mac.localhost:8481",
          "job": "trickster",
          "test_underscore": "works",      <---- test_underscore injects correctly
          "testlabel": "prom1"             <---- testlabel injects correctly
        },
        "values": [
          [
            ...
          ]
        ]
      }
    ]
  }
}
```

**Comment by jranson** [comment]
Thanks for the additional info. Glad to know _something_ is working right now 😂  I will read through this ^^ and see if there is something we can do in configuration or code to help with the above situation.

**Comment by tonychoe** [comment]
Tested with the trickster:main image and I see some improvement! 🤩 

The ALB query returns some result that Grafana can visualize.

But it seems just from one backend in the ALB pool and has some errors.

<img width="1743" alt="Image" src="https://github.com/user-attachments/assets/da8ef1cd-0911-466f-8e7d-1b2c8f9659ea" />

Copy of Grafana error
```
Status: 400. Message: response from prometheus couldn't be parsed. it is non-json: ReadObject: expect { or , or } or n, but found , error found in #1 byte of ...|��4|..., bigger context ...|��4�� BA[ �l[���AM�$�~��E�����f�A"|...
(Trace ID: 886d4441e00a8263d77cad1863cbfd7b)
```

Copy of Trickster error
```
time=2025-05-30T01:15:18.633586895Z app=trickster level=error event="error downloading url" detail="Post \"https://host.us-phoenix-1.domain.oraclecloud.com.:24230/prometheus/api/v1/query_range\": http: ContentLength=92 with Body length 0" url=https://host.us-phoenix-1.domain.oraclecloud.com.:24230/prometheus/api/v1/query_range

time=2025-05-30T01:15:19.266800502Z app=trickster level=error event="vector unmarshaling error" detail="no timerange query" provider=prometheus
]
time=2025-05-30T01:15:19.267232083Z app=trickster level=error event="vector unmarshaling error" detail="invalid character '\x1f' looking for beginning of value" provider=prometheus
```

**Comment by tonychoe** [comment]
Above test is a _range query_.

When I forced an _instant query_, ALB does not work and gets this error. 

<img width="1595" alt="Image" src="https://github.com/user-attachments/assets/44f9b039-765a-4e50-bb42-5950488af18b" />

**Comment by tonychoe** [comment]
Hi James (@jranson), did you have any luck to find an issue / solution? 

I wonder if the issue has anything to do with /prometheus path our Mimir has.

**Comment by jranson** [comment]
@tonychoe have you tried adjusting the `origin_url` value to account for `/prometheus` in the path? 

E.g.,   instead of `origin_url: https://example.com:9090` use `origin_url: https://example.com:9090/prometheus`

**Comment by tonychoe** [comment]
@jranson that's my current set up which is facing the issues mentioned at https://github.com/trickstercache/trickster/issues/843#issuecomment-2920860448 and after. 😢 

```
    backends:
      ap-sydney-1:
        healthcheck:
          expected_codes:
          - 200
          failure_threshold: 3
          headers:
            Authorization: xxxxxx
          host: host.ap-sydney-1.domain.com.:24230
          interval: 5000ms
          path: /prometheus/api/v1/status/buildinfo
          recovery_threshold: 3
          scheme: https
          timeout: 1000ms
          verb: GET
        origin_url: https://host.ap-sydney-1.domain.com.:24230/prometheus
        prometheus:
          labels:
            trickster_label: ap-sydney-1
        provider: prometheus
        req_rewriter_name: oc1_authentication
```
