### ISSUE TITLE
ALB with TSM mechanism returns time series from the first backend only

### ISSUE THREAD

**Issue by tonychoe** [trickstercache/trickster#844]
Hello Tricksters!

Much appreciate the Beta 3 release. 

Here's another issue I am facing with making the ALB with TSM mechanism working.

I have multiple backends under a pool. Somehow, my query to the ALB only returns the time series from the first backend in the pool. 

So, I've adjusted the order of backends in the pool, and I found it always returns the first backend's query result, but not the results from the other backends in the pool. 

For example, if I have the eu-frankfurt-1 on the top of the pool list, 

```
  global:
    alb:
      healthy_floor: 1
      mechanism: tsm
      pool:
      - eu-frankfurt-1
      - uk-london-1
      - us-ashburn-1
      - us-phoenix-1
      - ap-sydney-1
    provider: alb
```
I get the query result from eu-frankfurt-1 but not other backends.

<img width="1643" alt="Image" src="https://github.com/user-attachments/assets/43ad9d81-8224-4aae-8fa1-47f2162f3835" />

If I move uk-london-1 to the top in the list, 

```
  global:
    alb:
      healthy_floor: 1
      mechanism: tsm
      pool:
      - uk-london-1
      - eu-frankfurt-1
      - us-ashburn-1
      - us-phoenix-1
      - ap-sydney-1
    provider: alb
```
<img width="1640" alt="Image" src="https://github.com/user-attachments/assets/819e6728-89ef-4342-a8e6-260d417d8207" />

All backends are healthy and they return results when queried individually. 

<details>
<summary>Trickster configuration (click to expand)</summary>

Here's a copy of one of backend config

```
  us-phoenix-1:
    healthcheck:
      expected_codes:
      - 200
      failure_threshold: 3
      headers:
        XXX
      host: host.us-phoenix-1.domain.oraclecloud.com.
      interval: 5000ms
      path: /prometheus/api/v1/status/buildinfo
      recovery_threshold: 3
      scheme: https
      timeout: 1000ms
      verb: GET
    origin_url: https://host.us-phoenix-1.domain.oraclecloud.com.
    prometheus:
      labels:
        trickster_label: us-phoenix-1
    provider: prometheus
    req_rewriter_name: oc1_authentication
```

Here's a copy of the ALB config.
```
  global:
    alb:
      healthy_floor: 1
      mechanism: tsm
      pool:
      - eu-frankfurt-1
      - us-ashburn-1
      - us-phoenix-1
      - uk-london-1
      - ap-sydney-1
    provider: alb
```
</details>
